In [225]:
import matplotlib.pyplot as plt
import numpy as np
from itertools import product, combinations
import random
import pandas as pd
import plotly.express as px
from random import randint
import plotly.graph_objs as go

In [266]:
def plotly3d(x, y, z, title):
    df = {'x': x, 'y': y, 'z': z}
    fig = px.scatter_3d(df, x='x', y='y', z='z', title=title)
    fig.update_traces(marker=dict(size=3,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
    fig.show()

In [267]:
def plot3d(x, y, z, title):
    fig = plt.figure(figsize=(6,6))
    ax = fig.add_subplot(projection='3d')
    ax.scatter3D(x,y,z)
    ax.set_title(title)
    plt.tight_layout()
    plt.show()

In [304]:
def plot_with_vectors_u(X, Y, Z, U, s):
    points = go.Scatter3d( x = X,
                           y = Y,
                           z = Z,
                           mode = 'markers',
                           marker = dict( size = 2,
                                          color = 'darkslateblue')
                         )

    u1 = go.Scatter3d(     x = [0, s[0] * U[:, 0][0]],
                           y = [0, s[0] * U[:, 0][1]],
                           z = [0, s[0] * U[:, 0][2]],
                           marker = dict( size = 1,
                                          color = "rgb(250,3,0)"),
                           line = dict( color = "rgb(250,3,0)",
                                        width = 6)
                         )
    u2 = go.Scatter3d(     x = [0, s[1] * U[:, 1][0]],
                           y = [0, s[1] * U[:, 1][1]],
                           z = [0, s[1] * U[:, 1][2]],
                           marker = dict( size = 1,
                                          color = "rgb(250,253,0)"),
                           line = dict( color = "rgb(250,253,0)",
                                        width = 6)
                         )
    u3 = go.Scatter3d(     x = [0, s[2] * U[:, 2][0]],
                           y = [0, s[2] * U[:, 2][1]],
                           z = [0, s[2] * U[:, 2][2]],
                           marker = dict( size = 1,
                                          color = "rgb(0,253,0)"),
                           line = dict( color = "rgb(0,253,0)",
                                        width = 6)
                         )
    data = [points,u1,u2,u3]

    layout = go.Layout(margin = dict( l = 0,
                                      r = 0,
                                      b = 0,
                                      t = 0)
                      )
    fig = go.Figure(data=data,layout=layout)
    fig.show()


In [305]:
def plot_util(X, Y, Z, V1, V2, V3, title=''):

    points = go.Scatter3d( x = X,
                           y = Y,
                           z = Z,
                           mode = 'markers',
                           marker = dict( size = 2,
                                          color = 'darkslateblue')
                         )

    u1 = go.Scatter3d(     x = [0, V1[0]],
                           y = [0, V1[1]],
                           z = [0, V1[2]],
                           marker = dict( size = 1,
                                          color = 'rgb(250,3,0)'),
                           line = dict( color = "rgb(250,3,0)",
                                        width = 6)
                         )
    u2 = go.Scatter3d(     x = [0, V2[0]],
                           y = [0, V2[1]],
                           z = [0, V2[2]],
                           marker = dict( size = 1,
                                          color = "rgb(250,253,0)"),
                           line = dict( color = "rgb(250,253,0)",
                                        width = 6)
                         )
    u3 = go.Scatter3d(     x = [0, V3[0]],
                           y = [0, V3[1]],
                           z = [0, V3[2]],
                           marker = dict( size = 1,
                                          color = "rgb(0,253,0)"),
                           line = dict( color = "rgb(0,253,0)",
                                        width = 6)
                         )

    data = [points, u1, u2, u3]

    layout = go.Layout(margin = dict( l = 0,
                                      r = 0,
                                      b = 0,
                                      t = 0)
                      )
    fig = go.Figure(data=data,layout=layout)

    
    fig.show()


In [306]:
def get_sphere():
    X = []
    Y = []
    Z = []

    n = 1000
    for _ in range(n):
        s = random.uniform(0, 2*np.pi)
        t = random.uniform(0, np.pi)
        x = np.cos(s)*np.sin(t)
        y = np.sin(s)*np.sin(t)
        z = np.cos(t)
        X.append(x)
        Y.append(y)
        Z.append(z)
    return X, Y, Z
    

# Generate sphere

In [307]:
X, Y, Z = get_sphere()
    
plotly3d(X, Y, Z, "sphere")

In [308]:
A1 = np.array([[5, 2, 6],
              [3, 8, 4],
              [2, 3, 7]])
A2 = np.array([[1, 1, 1],
              [7, -5, 122],
              [1, 1, 1]])
A3 = np.array([[7, 12, 2],
              [2, 2, 1],
              [2, 9, 3]])

In [309]:
A1_X, A1_Y, A1_Z = [], [], []
A2_X, A2_Y, A2_Z = [], [], []
A3_X, A3_Y, A3_Z = [], [], []    

In [310]:
def transform(A, A_X, A_Y, A_Z):
    X, Y, Z = get_sphere()
    
    for x, y, z in zip(X,Y,Z):
        v = np.stack((x, y, z))
        res_x, res_y, res_z = A @ v
        A_X.append(res_x)
        A_Y.append(res_y)
        A_Z.append(res_z)

In [311]:
transform(A1, A1_X, A1_Y, A1_Z)
transform(A2, A2_X, A2_Y, A2_Z)
transform(A3, A3_X, A3_Y, A3_Z)

In [312]:
plotly3d(A1_X, A1_Y, A1_Z, "A1")

# Rank of matrix A2 is 2 so the result will be plane

In [313]:
plotly3d(A2_X, A2_Y, A2_Z, "A2")

In [314]:
plotly3d(A3_X, A3_Y, A3_Z, "A3")

# Singular Value Decomposition

In [315]:
U1, s1, VT1 = np.linalg.svd(A1)
print(U1),print(), print(s1), print(), print(VT1)

[[-0.54684865  0.54092808 -0.63902532]
 [-0.63274735 -0.76683978 -0.1076454 ]
 [-0.54825846  0.34547584  0.76161612]]

[13.66707349  4.9064195   2.26674873]

[[-0.41918281 -0.57074775 -0.70606853]
 [ 0.22319183 -0.81860807  0.52921285]
 [-0.88004044  0.0642482   0.47053266]]


(None, None, None, None, None)

In [316]:
plot_with_vectors_u(A1_X, A1_Y, A1_Z, U1, s1)

In [317]:
U2, s2, VT2 = np.linalg.svd(A2)
print(U2),print(), print(s2), print(), print(VT2)
plot_with_vectors_u(A2_X, A2_Y, A2_Z, U2, s2)

[[-8.29149438e-03  7.07058167e-01 -7.07106781e-01]
 [-9.99931249e-01 -1.17259438e-02  6.18406390e-17]
 [-8.29149438e-03  7.07058167e-01  7.07106781e-01]]

[1.22311310e+02 1.98584189e+00 3.99142147e-16]

[[-0.05736266  0.0407409  -0.99752178]
 [ 0.67076575  0.74162302 -0.00828304]
 [-0.73944765  0.66957858  0.06986907]]


In [318]:
U3, s3, VT3 = np.linalg.svd(A3)
print(U3),print(), print(s3), print(), print(VT3)
plot_with_vectors_u(A3_X, A3_Y, A3_Z, U3, s3)

[[-0.81786249 -0.51094632 -0.26464089]
 [-0.16468664 -0.23282342  0.95847356]
 [-0.55134314  0.82748239  0.1062715 ]]

[17.06876501  2.81596009  0.85301224]

[[-0.4193096  -0.88499733 -0.20238377]
 [-0.84777704  0.30197119  0.43599024]
 [ 0.32473613 -0.35439121  0.87689983]]


# one direction is 100 times more stretched than the direction with smallest strech, so the resulting matrix will be in approximation plane

In [319]:
def generate_special_matrix():
    """such that the ratio of biggest singular value and smallest is greater than 100"""
    while True:
        m = [[randint(0, 100000) for _ in range(3)] for _ in range(3)]
        U, S, V = np.linalg.svd(m)
        if S[0]/S[-1] > 100:
            return m    

In [321]:
m = generate_special_matrix()
Xm, Ym, Zm = [], [], []
m = np.array(m)
transform(m, Xm, Ym, Zm)

U, S, V = np.linalg.svd(m)
plot_with_vectors_u(Xm, Ym, Zm, U, S)

# Visualization of SVD
### V rotates 
### S stretches
### U rotates

In [322]:
A1 = np.array([[3, 7, 1],
              [20, 5, 3],
              [2, 1, 7]])

U, s, V = np.linalg.svd(A1)

s_x, s_y, s_z = get_sphere()
S = np.stack((s_x, s_y, s_z))
S.shape, V.shape

((3, 1000), (3, 3))

In [324]:
print('sphere')
X, Y, Z = S
plot_util(X, Y, Z, [0,0,1], [0,1,0], [1,0,0], "sphere")

print('V on sphere')
X, Y, Z = V @ S
plot_util(X, Y, Z,  V[0], V[1], V[2], "V @ S")

print("EV on sphere")
SEV = (np.diag(s) @ V) @ S
X, Y, Z = SEV
plot_util(X, Y, Z, V[0]@np.diag(s), V[1]@np.diag(s), V[2]@np.diag(s))

print("UEV on sphere")
SUEV = (U @ np.diag(s) @ V) @ S
X, Y, Z = SUEV
plot_util(X, Y, Z, s[0] * U[:, 0], s[1] * U[:, 1],s[2] * U[:, 2] )

print("Orginal matrix on sphere")
X, Y, Z = A1 @ S
plot_util(X, Y, Z, s[0] * U[:, 0], s[1] * U[:, 1],s[2] * U[:, 2] )


sphere


V on sphere


EV on sphere


UEV on sphere


Orginal matrix on sphere
